In [4]:
import pandas as pd
import requests

In [6]:
numberplates = pd.read_csv("numberplates.csv", dtype={
    "numberplate_id": str,
    "auto_id": 'Int64',
    "photo_index": 'Int64',
    "photo_id": 'Int64',
    "ordering": 'Int64',
    "partner_id": 'Int64'
})

In [8]:
numberplates["numberplate_id"] = numberplates["numberplate_id"].apply(lambda x: x[2:])
numberplates.head()

,numberplate_id,auto_id,number,createdAt,numberplate_url,photo_index,valid,photo_id,image_url,ordering,enabled,partner_id
0,2053838,55254138,B3278HI,2023-03-24 19:37:37,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,0,1.0,957649126,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,0,1.0,3
1,2053838,55254138,B3278HI,2023-03-24 19:37:37,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,0,1.0,957649128,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,1,1.0,3
2,2053838,55254138,B3278HI,2023-03-24 19:37:37,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,0,1.0,957649130,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,2,1.0,3
3,2053838,55254138,B3278HI,2023-03-24 19:37:37,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,0,1.0,957649132,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,3,1.0,3
4,2053838,55254138,B3278HI,2023-03-24 19:37:37,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,0,1.0,957649134,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,4,1.0,3

In [22]:
grouped = numberplates.groupby('auto_id').agg({
    'number': lambda x: x.iloc[0],
    'numberplate_url': lambda x: x.iloc[0],
    'image_url': lambda x: ','.join(x)
}).reset_index()
grouped.head()

,auto_id,number,numberplate_url,image_url
0,55254138,B3278HI,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...
1,55293911,01347OK,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...
2,55318880,KA7940KC,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...
3,55382833,AA0000AA,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...
4,55383512,BE6798EI,https://i1.rst.ua/oldcars/opel/astra/big/14002...,https://i1.rst.ua/oldcars/opel/astra/big/14002...

In [29]:
def numberplate_parse_old(numberplate_url):
    url = "http://dc.cherniy.net:2236/read?url="
    try:
        res = requests.get(f"{url}{numberplate_url}")
        data = res.json()
        return data["number_plates"][0]
    except Exception as e:
        print(e)
        return None

def numberplate_parse_new(numberplate_url):
    url = "http://localhost:3116/read?url="
    try:
        res = requests.get(f"{url}{numberplate_url}")
        data = res.json()
        return data["number_plates"][0]
    except Exception as e:
        print(e)
        return None

In [30]:
grouped["old"] = grouped["numberplate_url"].apply(numberplate_parse_old)
grouped["new"] = grouped["image_url"].apply(numberplate_parse_new)

Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
'number_plates'
'number_plates'
'number_plates'
list index out of range
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
'number_plates'
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)

In [36]:
grouped["new"] = grouped["image_url"].apply(numberplate_parse_new)
grouped.head(50)

Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
list index out of range
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)

,auto_id,number,numberplate_url,image_url,old,new
0,55254138,B3278HI,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,None,None
1,55293911,01347OK,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...,01347OK,01347OK
2,55318880,KA7940KC,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,9986B,None
3,55382833,AA0000AA,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BC4096MH,BC4096MH
4,55383512,BE6798EI,https://i1.rst.ua/oldcars/opel/astra/big/14002...,https://i1.rst.ua/oldcars/opel/astra/big/14002...,BH1965EA,AT999TT
5,55393830,BM7638BI,https://i0.rst.ua/oldcars/suzuki/swift/big/140...,https://i0.rst.ua/oldcars/suzuki/swift/big/140...,BM7638BI,BM7638BI
6,55395535,BM7839AA,https://i0.rst.ua/oldcars/vaz/2108/big/1400389...,https://i0.rst.ua/oldcars/vaz/2108/big/1400389...,BM7839AA,BM7839AA
7,55395947,88417MO,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,88417MO,88417MO
8,55396149,KA3789HA,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,KA3789HA,KA3789HA
9,55406743,50037AH,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,50037AH,None
10,55408307,AB1841EH,https://i0.rst.ua/oldcars/vaz/2114/big/1400516...,https://i0.rst.ua/oldcars/vaz/2114/big/1400516...,AB1841EH,AB1841EH
11,55422688,39029HI,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,None,39029HI
12,55427973,AT2978HM,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,AT2978HM,AT2978HM
13,55432226,28249PE,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,None,28249PE
14,55451166,BE0375EM,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,27146OK,27146OK
15,55471381,BX0522CA,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BX0522CA,BX0522CA
16,55477377,CB3170BE,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,CB3170BE,CB3170BE
17,55480865,CB6796EC,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,CB4724CC,CB4724CC
18,55524208,AE5783TX,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BT1891CB,BT1891CB
19,55535531,BH7687HT,https://i0.rst.ua/oldcars/honda/accord/big/140...,https://i0.rst.ua/oldcars/honda/accord/big/140...,BH7687H,BH7687H
20,55538772,39650KE,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,396AE,396AE
21,55555982,BM1636CX,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BM1636CX,BM1636CX
22,55573369,CA3785HP,https://i0.rst.ua/oldcars/peugeot/405/big/1401...,https://i0.rst.ua/oldcars/peugeot/405/big/1401...,CA3785HP,CA3785HP
23,55573926,AX8356AE,https://i0.rst.ua/oldcars/gaz/volga/big/140156...,https://i0.rst.ua/oldcars/gaz/volga/big/140156...,KX6356AE,KX6356AE
24,55574250,AE1005CP,https://i1.rst.ua/oldcars/volkswagen/jetta/big...,https://i1.rst.ua/oldcars/volkswagen/jetta/big...,AE1005CP,AE1005CP
25,55574356,ÂÊ9587ÂÌ,https://i1.rst.ua/oldcars/vaz/2109/big/1401548...,https://i1.rst.ua/oldcars/vaz/2109/big/1401548...,KBM909IP,KBM909IP
26,55574442,37646MA,https://i1.rst.ua/oldcars/vaz/2106/big/1401546...,https://i1.rst.ua/oldcars/vaz/2106/big/1401546...,37646MA,37646MA
27,55574510,AC6650CK,https://i0.rst.ua/oldcars/chevrolet/malibu/big...,https://i0.rst.ua/oldcars/chevrolet/malibu/big...,A6650CK,A0650CK
28,55574666,CB7146AO,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,469BO,71469BO
29,55575412,BX3136AA,https://i1.rst.ua/oldcars/vaz/niva/big/1401496...,https://i1.rst.ua/oldcars/vaz/niva/big/1401496...,A,UA
30,55581950,BM8493EB,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,None,None
31,55582788,34432KX,https://i0.rst.ua/oldcars/vaz/2101/big/1401937...,https://i0.rst.ua/oldcars/vaz/2101/big/1401937...,34432KX,34432KX
32,55584411,AA8284ET,https://i0.rst.ua/oldcars/gaz/volga/big/140198...,https://i0.rst.ua/oldcars/gaz/volga/big/140198...,AA8284ET,AA8284ET
33,55584472,AX6694HB,https://i0.rst.ua/oldcars/vaz/2106/big/1401983...,https://i0.rst.ua/oldcars/vaz/2106/big/1401983...,AX6694H,AX6694H
34,55584495,AE7402XA,https://i1.rst.ua/oldcars/volkswagen/passat/bi...,https://i1.rst.ua/oldcars/volkswagen/passat/bi...,None,None
35,55584505,BM0947AA,https://i1.rst.ua/oldcars/mercedes/s-class/big...,https://i1.rst.ua/oldcars/mercedes/s-class/big...,BM0947AA,BM0947AA
36,55584823,BA3343BO,https://i1.rst.ua/oldcars/mazda/626/big/140199...,https://i1.rst.ua/oldcars/mazda/626/big/140199...,None,None
37,55585647,AO1866KA,https://i0.rst.ua/oldcars/volkswagen/transport...,https://i0.rst.ua/oldcars/volkswagen/transport...,None,None
38,55586098,26360XA,https://i0.rst.ua/oldcars/vaz/2108/big/1401968...,https://i0.rst.ua/oldcars/vaz/2108/big/1401968...,26360XA,26360XA
39,55586168,55312CK,https://i0.rst.ua/oldcars/vaz/2109/big/1401965...,https://i0.rst.ua/oldcars/vaz/2109/big/1401965...,55312CK,55312CK
40,55586407,AX0267IT,https://i0.rst.ua/oldcars/audi/a6/big/14019197...,https://i0.rst.ua/oldcars/audi/a6/big/14019197...,AX0267IT,AX0267IT
41,55587039,76109ÕÊ,https://i0.rst.ua/oldcars/vaz/2105/big/1401776...,https://i0.rst.ua/oldcars/vaz/2105/big/1401776...,76109XK,76109XK
42,55602391,CA9787AP,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,CA9787AP,CA9787AP
43,55605012,41159XA,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BC6165ME,41159XA
44,55605401,BE1190EH,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BA1190EH,BA1190EH
45,55626621,AP4810IX,https://i1.rst.ua/oldcars/chevrolet/niva/big/1...,https://i1.rst.ua/oldcars/chevrolet/niva/big/1...,AP4810II,8927J
46,55627079,AB2125KE,https://i0.rst.ua/oldcars/volkswagen/cc/big/14...,https://i0.rst.ua/oldcars/volkswagen/cc/big/14...,AT2125KF,AT2125KF
47,55627182,AA7529PB,https://i0.rst.ua/oldcars/hyundai/ix35/big/140...,https://i0.rst.ua/oldcars/hyundai/ix35/big/140...,AA7529PB,AA7529PB
48,55627439,AO1079CB,https://i0.rst.ua/oldcars/volkswagen/transport...,https://i0.rst.ua/oldcars/volkswagen/transport...,AO1099CB,AO1099CB
49,55627696,BH7316PK,https://i0.rst.ua/oldcars/renault/master/big/1...,https://i0.rst.ua/oldcars/renault/master/big/1...,BH7316PK,BH7316PK

In [70]:
diff1 = grouped.query("number == new and number != old")
diff2 = grouped.query("number != new and number == old")
diff2

,auto_id,number,numberplate_url,image_url,old,new
9,55406743,50037AH,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,50037AH,None
53,55649419,BC5374PB,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BC5374PB,None
55,55650967,05267KO,https://i1.rst.ua/oldcars/maz/5549/big/1369051...,https://i1.rst.ua/oldcars/maz/5549/big/1369051...,05267KO,BI1700XI
65,55660789,AI5848OH,https://i1.rst.ua/oldcars/mercedes/vito/big/14...,https://i1.rst.ua/oldcars/mercedes/vito/big/14...,AI5848OH,AI584B
88,55673306,AB8363BE,https://i1.rst.ua/oldcars/mitsubishi/pajero/bi...,https://i1.rst.ua/oldcars/mitsubishi/pajero/bi...,AB8363BE,AXT833XK
95,55674149,AE0168PM,https://i1.rst.ua/oldcars/renault/grandscenic/...,https://i1.rst.ua/oldcars/renault/grandscenic/...,AE0168PM,None
101,55674916,61089EB,https://i1.rst.ua/oldcars/vaz/2109/big/1401988...,https://i1.rst.ua/oldcars/vaz/2109/big/1401988...,61089EB,None
113,55681892,KA4285HH,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,KA4285HH,None
141,55694654,BH6800EX,https://i0.rst.ua/oldcars/mercedes/s-class/big...,https://i0.rst.ua/oldcars/mercedes/s-class/big...,BH6800EX,None
178,55762546,04205AX,https://i0.rst.ua/oldcars/vaz/2106/big/1404103...,https://i0.rst.ua/oldcars/vaz/2106/big/1404103...,04205AX,04205A
213,55807396,CB2066EK,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,CB2066EK,None
224,55855650,AT3287BC,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,AT3287BC,AAF
232,55883162,BM4946EC,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BM4946EC,None
240,55921712,39956HE,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,39956HE,39956H
241,55922088,CE0132AK,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,CE0132AK,CE0132AA
256,56029292,AB9015IX,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,AB9015IX,HG117
273,56119864,AO2718CH,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,AO2718CH,UA
327,57391694,A3808IH,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,A3808IH,AA3808IH

In [64]:
grouped_fix = grouped.copy(deep=True)
grouped_fix.head()

,auto_id,number,numberplate_url,image_url,old,new
0,55254138,B3278HI,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,None,None
1,55293911,01347OK,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...,01347OK,01347OK
2,55318880,KA7940KC,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,9986B,None
3,55382833,AA0000AA,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BC4096MH,BC4096MH
4,55383512,BE6798EI,https://i1.rst.ua/oldcars/opel/astra/big/14002...,https://i1.rst.ua/oldcars/opel/astra/big/14002...,BH1965EA,AT999TT

In [67]:
grouped_fix["old"] = grouped_fix["old"].apply(lambda x: "" if x is None else x)
grouped_fix["new"] = grouped_fix["new"].apply(lambda x: "" if x is None else x)
grouped_fix.head()

,auto_id,number,numberplate_url,image_url,old,new
0,55254138,B3278HI,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,https://i1.rst.ua/oldcars/vaz/2106/big/1398878...,,
1,55293911,01347OK,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...,https://i0.rst.ua/oldcars/vaz/2108/big/1399317...,01347OK,01347OK
2,55318880,KA7940KC,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,9986B,
3,55382833,AA0000AA,https://ireland.apollo.olxcdn.com:443/v1/files...,https://ireland.apollo.olxcdn.com:443/v1/files...,BC4096MH,BC4096MH
4,55383512,BE6798EI,https://i1.rst.ua/oldcars/opel/astra/big/14002...,https://i1.rst.ua/oldcars/opel/astra/big/14002...,BH1965EA,AT999TT

In [53]:
old_count = grouped.query("number == old").shape[0]
new_count = grouped.query("number == new").shape[0]
total_count = grouped.shape[0]
failed = grouped.query("old.isnull() & new.isnull()").shape[0]
print(f"""old_count: {old_count}
new_count: {new_count}
total_count = {total_count}
failed = {failed}
total_photo_count = {numberplates.shape[0]}
delta = {new_count - old_count}
percentage = {(new_count - old_count) / new_count}
""")

old_count: 156
new_count: 173
total_count = 416
failed = 46
total_photo_count = 3608
delta = 17
percentage = 0.09826589595375723

In [2]:
old_count_fix = grouped_fix.query("number == old").shape[0]
new_count_fix = grouped_fix.query("number == new").shape[0]
total_count_fix = grouped_fix.shape[0]
failed_fix = grouped_fix.query("old == '' and new == ''").shape[0]
print(f"""old_count: {old_count_fix}
new_count: {new_count_fix}
total_count = {total_count_fix}
failed = {failed_fix}
total_photo_count = {numberplates.shape[0]}
delta = {new_count_fix - old_count_fix}
percentage = {(new_count_fix - old_count_fix) / new_count_fix}
""")

NameError: name 'grouped_fix' is not defined

In [43]:
grouped.to_csv("result.csv", index=None)

In [5]:
grouped = pd.read_csv("result.csv")

In [7]:
failed = grouped.query("old.isnull() & new.isnull()")
failed.iloc[0]["image_url"]

'https://i1.rst.ua/oldcars/vaz/2106/big/13988781-2.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-1.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-3.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-4.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-5.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-6.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-7.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-8.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-9.jpg,https://i1.rst.ua/oldcars/vaz/2106/big/13988781-10.jpg'